export const SET_USER_LOGIN_MODAL = 'SET_USER_LOGIN_MODAL';
export const SET_USER_SIGNUP_MODAL = 'SET_USER_SIGNUP_MODAL';
export const SET_WISHLIST_DRAWER = 'SET_WISHLIST_DRAWER';
export const SET_CART_DRAWER = 'SET_CART_DRAWER';
