const appTypes = {};

appTypes.TOGGLE_DRAWER = 'TOGGLE_DRAWER';
appTypes.USER_LOGIN_TOGGLE_MODAL = 'USER_LOGIN_TOGGLE_MODAL';
appTypes.USER_SIGNUP_TOGGLE_MODAL = 'USER_SIGNUP_TOGGLE_MODAL';

export default { appTypes };
